/*
 * This file was generated by the Gradle 'init' task.
 */
val projectName = "KUtils"
val kotlinVersion = "1.3.72"


group = "me.jakejmattson"
version = "0.17.0"

plugins {
    java
    `maven-publish`
    signing
    id("com.github.ben-manes.versions") version "0.28.0"
}

repositories {
    mavenLocal()
    mavenCentral()

    maven {
        url = uri("https://jcenter.bintray.com")
    }

    maven {
        url = uri("https://jitpack.io")
    }
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.7")
    implementation("org.reflections:reflections:0.9.12")
    implementation("org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.72")
    implementation("org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.3.72")
    implementation("org.jetbrains.kotlin:kotlin-script-runtime:1.3.72")
    implementation("org.jetbrains.kotlin:kotlin-script-util:1.3.72")
    implementation("net.dv8tion:JDA:4.1.1_155")
    implementation("com.google.code.gson:gson:2.8.6")
    implementation("com.google.guava:guava:29.0-jre")
    implementation("org.apache.commons:commons-text:1.8")
    implementation("org.slf4j:slf4j-simple:1.7.30")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.0-M1")
    testImplementation("io.mockk:mockk:1.10.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.4.2")
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

sourceSets {
    main {
        java {
            srcDir("src/main/kotlin")
        }
    }

    test {
        java {
            srcDir("src/test/kotlin")
        }
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.test {
    useJUnitPlatform()
}

publishing {
    publications {
        create<MavenPublication>(projectName) {
            artifactId = projectName
            from(components["java"])
            pom {
                name.set("KUtils")
                description.set("A Kotlin wrapper for the Discord API.")
                url.set("https://gitlab.com/JakeJMattson/KUtils/")
                licenses {
                    license {
                        name.set("MIT")
                        url.set("https://opensource.org/licenses/MIT")
                    }
                }
                developers {
                    developer {
                        id.set("JakeJMattson")
                        name.set("Jake Mattson")
                        email.set("JakeJMattson@gmail.com")
                    }
                }
            }
        }
    }
}

signing {
    sign(publishing.publications["KUtils"])
}